var azlyricsfour_output = [Verse 1:],
We just got out the club,
And we drunk as fuck,
We both horny, horny,
Got my main bitch in my bed,
So we can't go there,
But we've got this backseat, backseat,
I got this magnum in my pocket,
I'm getting head off in this cockpit,
I got her screaming and hollering,
I let her ride it while I'm watching,[Hook:],
While I watch that booty popping,
Booty popping, booty popping, booty booty popping,
While I watch that booty popping,
Booty popping, booty popping, booty booty popping,[Verse 2:],
I got this drank in my cup, this kush going on,
Now I'm zoning, zoning,
I put that pill on her tong, some smoke in her lungs,
Now she's floating, floating,
I got these bandz in my pocket,,
I throw em up like a rocket,
Girl show me why you deserve it,,
Twerk, twerk,
Show me why you deserve it,,
Twerk, twerk,[Hook:],
While I watch that booty popping,
Booty popping, booty popping, booty booty popping,
While I watch that booty popping,
Booty popping, booty popping, booty booty popping,[Bridge:],
We just got out the club,
And we drunk as fuck,
We both horny, horny,[Hook:],
While I watch that booty popping,
Booty popping, booty popping, booty booty popping,
While I watch that booty popping,
Booty popping, booty popping, booty booty popping
, Submit Corrections,
mixtape: ,"Beach House", (2012),My Cabana,Zone'n,Know Y I Came,Another One,4 A Young,That's All,Mi$$ion,DTF,Infatuated,Hold Up,Booty Poppin,Time
