var azlyricsthree_output = 
Ahh ah ah ,[x4],
Oh baby girl you got me so mixed up inside,
I don't know if I can't handle it..,
So baby tell me what I gotta do to make it right..,
I promise Im not scandalous,
Yeah!,
Your just a booty call,
Booty Call!,
Will you be my booty call?,
Booty Call!,
Will you my booty call?,
Drop those panties to the floor! ,[x2],
Nasty girls know me like what,
Call your girl to give me some,
Drop it girl go take it back,
I'll take you to the candy shack,
Like jolly ranchers sugar daddys,
Chocolate covered booty panties,
Lots of women in my cadi,
It's gonna get a little nasty,
E-40!,
Ohh!,
Lets go start another party,
Smoke a little chronic and get naughty,
Pop a few drinks and get sloppy,
Drunk, Crunk,
Girl you got a big ol donk (donk),
Look at the junk in your trunk (trunk),
I like your lady lumps (lumps),
Looking in those pants,
I know a couple dudes who give you all they money if you dance,
Get nasty girl get nasty ,[x3],
And shake it like chocolate milk,
Yeah!,
Your just a booty call,
Booty Call!,
Will you be my booty call?,
Booty Call!,
Will you my booty call?,
Drop those panties to the floor! ,[x2],
Oh baby girl I see your photos on myspace,
You look so beautiful,
So what I gotta do to take you to my place,
So you can be my booty girl..,
Get nasty girl get nasty ,[x3],
And shake it like chocolate milk,
Yeah!,
Your just a booty call,
Booty Call!,
Will you be my booty call?,
Booty Call!,
Will you my booty call?,
Drop those panties to the floor! ,[x2],
Now drop it girl go shake that ass,
I wanna see you make it clap,
Like clap clap clap clap clap clap,
Oh yeah she knows the way I want it,
Gucci boots with applebottoms,
Look at you, you want my body,
Let's go start another party,
Get nasty girl get nasty ,[x3],
And shake it like chocolate milk,
Yeah!,
Your just a booty call,
Booty Call!,
Will you be my booty call?,
Booty Call!,
Will you my booty call?,
Drop those panties to the floor! ,[x2],
You can be my booty call..!
, Submit Corrections,Writer(s): Shaznay Lewis, Karl Clive Jr. Gordon,
album: ,"I'm Not A Fan, But The Kids Like It!", (2009),Freaxx,Skeet Skeet,Booty Call,Get Crunk!,Yellow Bus,Get Up,Jealousy,Poppin',40 Oz.,Sex Toys,Rockstar,Schitzo,Scene Girls,Tipsy,I'm Sorry